"""add revision to traffic_allocations

Revision ID: 060d50b59428
Revises: 227d44f8bb86
Create Date: 2026-08-14 22:39:13.910863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060d50b59428'
down_revision: Union[str, Sequence[str], None] = '227d44f8bb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='1' so existing rows get a real value in the same ALTER
    # TABLE - same pattern as inconclusive_retry_count/automation_paused. This is
    # a one-time cold-start baseline for any deployment that already existed
    # before this migration: its actual traffic-change history obviously started
    # earlier than "revision 1", but reconciliation only needs revision to be
    # monotonic *going forward* from here, not to reflect true historical count.
    op.add_column(
        "traffic_allocations",
        sa.Column("revision", sa.Integer(), nullable=False, server_default="1"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traffic_allocations', 'revision')
    # ### end Alembic commands ###
