"""add policy_config and inconclusive_retry_count to deployments

Revision ID: 0ad85e539731
Revises: c5809b3213e2
Create Date: 2026-08-03 23:28:32.899776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad85e539731'
down_revision: Union[str, Sequence[str], None] = 'c5809b3213e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('policy_config', sa.JSON(), nullable=True))
    op.add_column(
        'deployments',
        sa.Column('inconclusive_retry_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'inconclusive_retry_count')
    op.drop_column('deployments', 'policy_config')
    # ### end Alembic commands ###
