"""add positive_label_count to policy_evaluations

Revision ID: 13eb918c81c9
Revises: 2b72e841ab9d
Create Date: 2026-08-14 20:45:06.042424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13eb918c81c9'
down_revision: Union[str, Sequence[str], None] = '2b72e841ab9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_evaluations', sa.Column('positive_label_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_evaluations', 'positive_label_count')
    # ### end Alembic commands ###
