"""add automation_paused to deployments

Revision ID: 227d44f8bb86
Revises: 13eb918c81c9
Create Date: 2026-08-14 21:52:30.274712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227d44f8bb86'
down_revision: Union[str, Sequence[str], None] = '13eb918c81c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='0' (not just the model's Python-side default=False) so
    # existing rows get a real, non-null value in the same ALTER TABLE - matches
    # the pattern used for inconclusive_retry_count in
    # 0ad85e539731_add_policy_config_and_inconclusive_.py.
    op.add_column(
        "deployments",
        sa.Column("automation_paused", sa.Boolean(), nullable=False, server_default="0"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'automation_paused')
    # ### end Alembic commands ###
