"""add active-deployment-per-model partial unique index

Enforces "at most one non-terminal (not PROMOTED/ROLLED_BACK/FAILED) deployment
per model_name" as a DB-level constraint, not just the app-level check-then-act
pre-check in control_plane.service.create_deployment (which races: two concurrent
requests can both read "no active deployment" before either commits). See
app/control_plane/models.py's Deployment.__table_args__ (kept in sync with this
migration - ORM metadata is also what the test suite's Base.metadata.create_all
builds from) and docs/DESIGN_NOTES.md.

Broader than service.ACTIVE_STATUSES on purpose: INCONCLUSIVE counts as
"non-terminal" here (a human still has to promote/roll it back), even though
get_active_deployment() itself only looks at CANARY_RUNNING/EVALUATING for a
different, narrower question (what the router should sync from).

Refuses to apply against data that already violates the invariant, rather than
silently deleting or picking a winner - see the guard at the top of upgrade().

Revision ID: 428fd87f025a
Revises: e62bc551280e
Create Date: 2026-08-14 15:46:32.194961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428fd87f025a'
down_revision: Union[str, Sequence[str], None] = 'e62bc551280e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TERMINAL_STATUSES_SQL = "'FAILED', 'PROMOTED', 'ROLLED_BACK'"


def upgrade() -> None:
    connection = op.get_bind()
    violations = connection.execute(
        sa.text(
            f"""
            SELECT model_name, COUNT(*) AS active_count
            FROM deployments
            WHERE status NOT IN ({_TERMINAL_STATUSES_SQL})
            GROUP BY model_name
            HAVING COUNT(*) > 1
            """
        )
    ).fetchall()
    if violations:
        details = ", ".join(
            f"'{row.model_name}' ({row.active_count} non-terminal deployments)"
            for row in violations
        )
        raise RuntimeError(
            "Cannot add uq_deployments_active_per_model: existing data already "
            "violates the invariant it enforces (more than one non-terminal "
            f"deployment for the same model_name): {details}. Promote or roll "
            "back the extra deployment(s) for each model listed above (or delete "
            "stale demo/benchmark rows) and re-run this migration - it will not "
            "silently pick a winner and delete data for you."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_deployments_active_per_model', 'deployments', ['model_name'], unique=True, sqlite_where=sa.text(f"status NOT IN ({_TERMINAL_STATUSES_SQL})"), postgresql_where=sa.text(f"status NOT IN ({_TERMINAL_STATUSES_SQL})"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_deployments_active_per_model', table_name='deployments', sqlite_where=sa.text(f"status NOT IN ({_TERMINAL_STATUSES_SQL})"), postgresql_where=sa.text(f"status NOT IN ({_TERMINAL_STATUSES_SQL})"))
    # ### end Alembic commands ###
