"""add deployment control plane tables

Revision ID: 793fb0c84029
Revises: 
Create Date: 2026-08-03 18:17:39.253618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793fb0c84029'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('stable_version', sa.String(length=100), nullable=False),
    sa.Column('canary_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DEPLOYING', 'CANARY_RUNNING', 'EVALUATING', 'PROMOTING', 'PROMOTED', 'ROLLING_BACK', 'ROLLED_BACK', 'FAILED', 'INCONCLUSIVE', name='deploymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_idempotency_key'), 'deployments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_deployments_model_name'), 'deployments', ['model_name'], unique=False)
    op.create_table('deployment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_allocations')
    op.drop_table('deployment_events')
    op.drop_index(op.f('ix_deployments_model_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_idempotency_key'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
