"""authoritative routing state and durable ground truth labels

Revision ID: 7d87fbdc22b8
Revises: 060d50b59428
Create Date: 2026-08-15 14:07:38.945343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d87fbdc22b8'
down_revision: Union[str, Sequence[str], None] = '060d50b59428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_truth_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('actual_label', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ground_truth_labels_prediction_id'), 'ground_truth_labels', ['prediction_id'], unique=True)
    op.create_table('routing_generations',
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('model_name')
    )
    # ### end Alembic commands ###

    # --- data migration: carry existing labels forward before dropping their old
    # homes (pending_labels, prediction_metrics.actual_label/label_ingested_at) -
    # see GroundTruthLabel's docstring for why this table now exists at all. The
    # migration-only id (lower(hex(randomblob(16)))) is not a real UUID4, just a
    # unique 32-hex-char primary key value for these already-historical rows -
    # nothing outside this migration ever reads it back out and compares format.

    # Labels already matched to a PredictionMetric: occurred_at was never stored
    # for these (PredictionMetric had no such column before this migration), so
    # label_ingested_at is carried into both occurred_at and ingested_at - an
    # approximation (the real-world occurrence time is gone), not a bug.
    op.execute(
        """
        INSERT INTO ground_truth_labels (id, prediction_id, actual_label, occurred_at, ingested_at)
        SELECT lower(hex(randomblob(16))), prediction_id, actual_label, label_ingested_at, label_ingested_at
        FROM prediction_metrics
        WHERE actual_label IS NOT NULL AND prediction_id IS NOT NULL
        """
    )
    # Labels that never found a matching PredictionMetric (still sitting in
    # pending_labels) - these do have a real occurred_at, carried forward as-is.
    # The WHERE NOT IN guards against a prediction_id somehow present in both
    # places (shouldn't happen - PendingLabel is deleted the moment it's matched -
    # but a migration touching historical data shouldn't assume that never broke).
    op.execute(
        """
        INSERT INTO ground_truth_labels (id, prediction_id, actual_label, occurred_at, ingested_at)
        SELECT lower(hex(randomblob(16))), prediction_id, actual_label, occurred_at, ingested_at
        FROM pending_labels
        WHERE prediction_id NOT IN (SELECT prediction_id FROM ground_truth_labels)
        """
    )
    # routing_generations backfill: seed each model's counter from the highest
    # revision any of its deployments' TrafficAllocation already reached, so the
    # first post-migration push continues from there instead of resetting to 1
    # (which could be lower than what the router currently has observed and
    # applied, and would then be spuriously rejected as stale - see
    # RoutingGeneration's docstring).
    op.execute(
        """
        INSERT INTO routing_generations (model_name, generation)
        SELECT d.model_name, MAX(ta.revision)
        FROM traffic_allocations ta
        JOIN deployments d ON d.id = ta.deployment_id
        GROUP BY d.model_name
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_labels_prediction_id'), table_name='pending_labels')
    op.drop_table('pending_labels')
    op.drop_column('prediction_metrics', 'actual_label')
    op.drop_column('prediction_metrics', 'label_ingested_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Data loss note: labels that only ever existed in ground_truth_labels (the
    common case going forward) are not written back onto prediction_metrics or
    pending_labels here - a downgrade recreates the old *shape*, not the
    Sprint-14-and-later label data within it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_metrics', sa.Column('label_ingested_at', sa.DATETIME(), nullable=True))
    op.add_column('prediction_metrics', sa.Column('actual_label', sa.INTEGER(), nullable=True))
    op.create_table('pending_labels',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('prediction_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('actual_label', sa.INTEGER(), nullable=False),
    sa.Column('occurred_at', sa.DATETIME(), nullable=False),
    sa.Column('ingested_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_labels_prediction_id'), 'pending_labels', ['prediction_id'], unique=1)
    op.drop_table('routing_generations')
    op.drop_index(op.f('ix_ground_truth_labels_prediction_id'), table_name='ground_truth_labels')
    op.drop_table('ground_truth_labels')
    # ### end Alembic commands ###
