"""add policy_evaluations table

Revision ID: c5809b3213e2
Revises: 259ef1fbee76
Create Date: 2026-08-03 23:14:39.518173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5809b3213e2'
down_revision: Union[str, Sequence[str], None] = '259ef1fbee76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('policy_name', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'INCONCLUSIVE', name='policyevaluationresult', native_enum=False, length=16), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_deployment_id'), 'policy_evaluations', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_evaluated_at'), 'policy_evaluations', ['evaluated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_evaluations_evaluated_at'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_deployment_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    # ### end Alembic commands ###
