"""add deployment optimistic locking + policy evaluation context snapshot

Two related correctness fixes from the same mini-sprint:
- deployments.version_id (+ updated_at): SQLAlchemy optimistic-locking column so a
  concurrent promote/rollback/advance-traffic/record-inconclusive that read a stale
  copy of a deployment loses its commit (409) instead of silently overwriting a
  newer one.
- policy_evaluations.{evaluation_window_seconds,stable_weight,canary_weight,
  stable_sample_count,canary_sample_count}: a snapshot of the deployment's own
  context at the moment each check ran, so the timeline's explanation for an old
  check reflects what was true *then*, not the deployment's current traffic split.
  All nullable - existing rows get NULL and explain.py falls back to an explicitly
  flagged "estimated" explanation for them.

Revision ID: e62bc551280e
Revises: d6d66865b269
Create Date: 2026-08-10 00:14:49.263053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62bc551280e'
down_revision: Union[str, Sequence[str], None] = 'd6d66865b269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('deployments', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('policy_evaluations', sa.Column('evaluation_window_seconds', sa.Integer(), nullable=True))
    op.add_column('policy_evaluations', sa.Column('stable_weight', sa.Float(), nullable=True))
    op.add_column('policy_evaluations', sa.Column('canary_weight', sa.Float(), nullable=True))
    op.add_column('policy_evaluations', sa.Column('stable_sample_count', sa.Integer(), nullable=True))
    op.add_column('policy_evaluations', sa.Column('canary_sample_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_evaluations', 'canary_sample_count')
    op.drop_column('policy_evaluations', 'stable_sample_count')
    op.drop_column('policy_evaluations', 'canary_weight')
    op.drop_column('policy_evaluations', 'stable_weight')
    op.drop_column('policy_evaluations', 'evaluation_window_seconds')
    op.drop_column('deployments', 'version_id')
    op.drop_column('deployments', 'updated_at')
    # ### end Alembic commands ###
